[versions]
kotlin = "1.9.21"
gson = "2.12.1"
kotlinxCollectionsImmutable = "0.3.8"
junit = "5.11.4"
mavenPublish = "0.30.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "junit" }
